config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # CREATE
  get 'reviews/new', to: 'reviews#new'
  post 'reviews', to: 'reviews#create'
  # READ
  get 'reviews/index'
  get 'reviews/:id', to: 'reviews#show', as: 'review'
  # UPDATE
  get 'reviews/:id/edit', to: 'reviews#edit', as: :review_edit
  patch 'reviews/:id', to: 'reviews#update'
  # DELETE
  delete 'reviews/:id', to: 'reviews#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'gustos/new', to: 'gustos#new'
  post 'gustos', to: 'gustos#create'
  # READ
  get 'gustos/index', to: 'gustos#index'
  get 'gustos/:id', to: 'gustos#show', as: 'gusto'
  # UPDATE
  get 'gustos/:id/edit', to: 'gustos#edit', as: :gusto_edit
  patch 'gustos/:id', to: 'gustos#update'
  # DELETE
  delete 'gustos/:id', to: 'gustos#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'comunas/new', to: 'comunas#new'
  post 'comunas', to: 'comunas#create'
  # READ
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'
  # UPDATE
  get 'comunas/:id/edit', to: 'comunas#edit', as: :comuna_edit
  patch 'comunas/:id', to: 'comunas#update'
  # DELETE
  delete 'comunas/:id', to: 'comunas#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",
                                                   registrations: "users/registrations" }
  # READ
  get 'users/index', to: 'users#index'
  get 'users/:id', to: 'users#show', as: 'user'

  # ------------------------------------------------------------------------------------------------
  devise_for :locals, path: 'locals', controllers: { sessions: "locals/sessions",
                                                     registrations: "locals/registrations" }
  # READ
  get 'locals/index', to: 'locals#index'
  get 'locals/:id', to: 'locals#show', as: 'local'
  # DELETE
  delete 'locals/:id', to: 'locals#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'matches', to: 'matches#create'
  # READ
  get 'matches/show_especial', to: 'matches#show_especial'
  get 'matches/:id', to: 'matches#management_local_view', as: 'match'
  # UPDATE
  patch 'matches/update', to: 'matches#update'
  patch 'matches/update_rejections', to: 'matches#update_rejections'
  # patch 'matches/management_local_view', to: 'matches#management_local_view'
  patch 'matches/update_local_and_boolean', to: 'matches#update_local_and_boolean'
  patch 'matches/accept_local', to: 'matches#accept_local'
  patch 'matches/change_local', to: 'matches#change_local'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'add_gusto', to: 'users#add_gusto'
  # DELETE
  delete 'remove_gusto', to: 'users#remove_gusto'
end

app/models/local.rb
class Local < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nombre, presence: true
  has_many :reviews, dependent: :destroy
  belongs_to :comuna
  has_many :matches, dependent: :nullify
end

app/controllers/locals/confirmations_controller.rb
# frozen_string_literal: true

class Locals::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/locals/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Locals::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/locals/passwords_controller.rb
# frozen_string_literal: true

class Locals::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/locals/registrations_controller.rb
# frozen_string_literal: true

class Locals::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/locals/sessions_controller.rb
# frozen_string_literal: true

class Locals::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/locals/unlocks_controller.rb
# frozen_string_literal: true

class Locals::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  def index
    @locals = Local.all
    @promedios
  end

  def show
    @local = Local.find(params[:id])
    @promedio = get_promedio_local(@local)
  end

  def destroy
    @local = Local.find(params[:id])
    @local.destroy
    redirect_to locals_index_path, notice: "Local eliminado con éxito"
  end

  def get_promedio_local(local)
    a = 0.0
    local.reviews.each do |review|
      a += review.calificacion
    end
    b = local.reviews.length
    b != 0 ? a / b : 0
  end

  helper_method :get_promedio_local
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/locals/index.html.erb
<section id="match_img_2" class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column"></div>
        <div class="column">
          <h1 class="title has-text-white has-text-centered">Locales</h1>
          <div  class="box">
            <div id="size_fixed" class="container">
              <table class="table">
                <tbody>
                  <% @locals.each do |local| %>
                    <tr>
                      <td> <%= local.nombre %> </td>
                      <td> <%= link_to "Ver detalles", local_path(local.id), class:"button is-primary" %> </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <button id="buttonuser" class="button">
            <%= link_to "Volver a la pagina principal", root_path %>
          </button>
        </div>
        <div class="column"></div>
      </div>
    </div>
  </div>
</section>

app/views/locals/show.html.erb
<section id="user_index_img" class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
                <h1 class="title is-1"><%= @local.nombre %></h1>
                <h6 class="subtitle is-6"><%= @local.comuna.nombre %></h6>
                <p><%= @local.descripcion %></p>
                <div class="columns">
                  <div class="column"></div>
                  <div class="column">
                    <% if not @local.place_id %>
                    <p>Ubicación no disponible</p>
                    <% else %>
                    <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:<%= @local.place_id %>&key=<%= Rails.application.credentials[:google_maps_api_key] %>" allowfullscreen></iframe> 
                    <% end %>
                  </div>
                  <div class="column"></div>
                </div>
            </div>
            <nav class="level is-mobile">
              <div class="level-left">
                <p><strong>Calificación: </strong><%= @promedio != 0 ? @promedio : "Este local no tiene reviews" %></p>
              </div>
              <div class="level-right">
                <a class="level-item">
                  <%= link_to "Ver reviews de este local", reviews_index_path(local_id: @local.id), class:"button" %>
                </a>
                <a class="level-item">
                  <% if current_user %>
                    <%= link_to "Crear nueva review", reviews_new_path(local_id: @local.id), class:"button" %>
                  <% end %>
                </a>
              </div>
            </nav>
          </div>
        </article>

      </div>
        <button id="buttonuser" class="button">
          <%= link_to "Volver al listado de Locales", locals_index_path %>
        </button>
      <% if current_admin %>
        <button id="buttonuser" class="button">
              <%= link_to "Eliminar este local", local_path(@local.id), method: :delete, data: {confirm: "Está seguro?"} %>
        </button>
    <% end %>
    </div>
  </div>
</section>