config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # CREATE
  get 'reviews/new', to: 'reviews#new'
  post 'reviews', to: 'reviews#create'
  # READ
  get 'reviews/index'
  get 'reviews/:id', to: 'reviews#show', as: 'review'
  # UPDATE
  get 'reviews/:id/edit', to: 'reviews#edit', as: :review_edit
  patch 'reviews/:id', to: 'reviews#update'
  # DELETE
  delete 'reviews/:id', to: 'reviews#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'gustos/new', to: 'gustos#new'
  post 'gustos', to: 'gustos#create'
  # READ
  get 'gustos/index', to: 'gustos#index'
  get 'gustos/:id', to: 'gustos#show', as: 'gusto'
  # UPDATE
  get 'gustos/:id/edit', to: 'gustos#edit', as: :gusto_edit
  patch 'gustos/:id', to: 'gustos#update'
  # DELETE
  delete 'gustos/:id', to: 'gustos#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'comunas/new', to: 'comunas#new'
  post 'comunas', to: 'comunas#create'
  # READ
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'
  # UPDATE
  get 'comunas/:id/edit', to: 'comunas#edit', as: :comuna_edit
  patch 'comunas/:id', to: 'comunas#update'
  # DELETE
  delete 'comunas/:id', to: 'comunas#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",
                                                   registrations: "users/registrations" }
  # READ
  get 'users/index', to: 'users#index'
  get 'users/:id', to: 'users#show', as: 'user'

  # ------------------------------------------------------------------------------------------------
  devise_for :locals, path: 'locals', controllers: { sessions: "locals/sessions",
                                                     registrations: "locals/registrations" }
  # READ
  get 'locals/index', to: 'locals#index'
  get 'locals/:id', to: 'locals#show', as: 'local'
  # DELETE
  delete 'locals/:id', to: 'locals#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'matches', to: 'matches#create'
  # READ
  get 'matches/show_especial', to: 'matches#show_especial'
  get 'matches/:id', to: 'matches#management_local_view', as: 'match'
  # UPDATE
  patch 'matches/update', to: 'matches#update'
  patch 'matches/update_rejections', to: 'matches#update_rejections'
  # patch 'matches/management_local_view', to: 'matches#management_local_view'
  patch 'matches/update_local_and_boolean', to: 'matches#update_local_and_boolean'
  patch 'matches/accept_local', to: 'matches#accept_local'
  patch 'matches/change_local', to: 'matches#change_local'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'add_gusto', to: 'users#add_gusto'
  # DELETE
  delete 'remove_gusto', to: 'users#remove_gusto'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_adminhome.html.erb
<section class="hero is-fullheight">
<div class="hero-body">
  <div class="container">
    <p> Bienvenido </p>
    <p> Este es el panel de control del administrador <%= current_admin.email %> </p>
    <p>
      <%= link_to "Ver el listado de comunas", comunas_index_path %>
    </p>
    <p>
      <%= link_to "Ver el listado de gustos", gustos_index_path %>
    </p>
    <p>
      <%= link_to "Ver el listado de locales", locals_index_path %>
    </p>
    <p>
      <%= link_to "Ver el listado de reviews", reviews_index_path %>
    </p>
    <p>
      <%= link_to "Cerrar Sesión", destroy_admin_session_path, method: :delete %>
    </p>    
  </div>
</div>
</section>

app/views/home/_defaulthome.html.erb
<section id="default_img" class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-black">
        Bienvenido
      </h1>
      <h2 class="subtitle has-text-black">
        ¿Estas listo para encontrar el amor?
      </h2>
    </div>
  </div>
</section>

app/views/home/_localhome.html.erb
  <section class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
      <p> Bienvenido </p>
      <p> Este es el portal del local <%= current_local.nombre %> </p>
      <p>
        <%= link_to "Ver las reviews", reviews_index_path(local_id: current_local.id) %>
      </p>       
      </div>
    </div>
  </section>

app/views/home/_userhome.html.erb
<section id="user_img" class="hero is-fullheight">
  <div class="hero-body">
    <div id="centrado" class="container">
        <h1 class="title has-text-white">
        Aquí podrás encontrar tu cita ideal.
        </h1>
        <button id="buttonuser" class="button is-large">
            <%= link_to "Conoce otros Usuari@s", users_index_path, class:"has-text-black" %>
        </button>
        <button id="buttonuser" class="button has-text-black is-large">
            <%= link_to "Matches", matches_show_especial_path, class:"has-text-black" %>
        </button>
    </div>
  </div>
</section>
<section class="hero">
  <div class="hero-body">
    <div class="container">
        <div class="tile is-ancestor">
          <div class="tile is-4 is-vertical is-parent">
            <div class="tile is-child box">
                <% if current_user.imagen.attached? %>
                    <figure class="image is-4by3">
                      <%= image_tag(current_user.imagen) %>
                    </figure>
                <% else%>
                    <figure class="image is-4by3">
                        <img src="https://bulma.io/images/placeholders/640x480.png">
                    </figure>
                <% end %>
            </div>
          </div>
          <div class="tile is-parent">
            <div class="tile is-child box">
              <p class="title"><%= current_user.nombre%></p>
              <p><%=current_user.descripcion%></p>
            </div>
          </div>
        </div>
        <button id="buttonuser" class="button has-text-black is-large">
            <%= link_to "Ver historial de reviews", reviews_index_path, class:"has-text-black" %>
        </button>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<% if current_user %>
    <%= render "home/userhome" %>
<% elsif current_local %>
    <%= render "home/localhome" %>
<% elsif current_admin %>
    <%= render "home/adminhome" %>
<% else %>
    <%= render "home/defaulthome" %>
<% end %>