config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # CREATE
  get 'reviews/new', to: 'reviews#new'
  post 'reviews', to: 'reviews#create'
  # READ
  get 'reviews/index'
  get 'reviews/:id', to: 'reviews#show', as: 'review'
  # UPDATE
  get 'reviews/:id/edit', to: 'reviews#edit', as: :review_edit
  patch 'reviews/:id', to: 'reviews#update'
  # DELETE
  delete 'reviews/:id', to: 'reviews#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'gustos/new', to: 'gustos#new'
  post 'gustos', to: 'gustos#create'
  # READ
  get 'gustos/index', to: 'gustos#index'
  get 'gustos/:id', to: 'gustos#show', as: 'gusto'
  # UPDATE
  get 'gustos/:id/edit', to: 'gustos#edit', as: :gusto_edit
  patch 'gustos/:id', to: 'gustos#update'
  # DELETE
  delete 'gustos/:id', to: 'gustos#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'comunas/new', to: 'comunas#new'
  post 'comunas', to: 'comunas#create'
  # READ
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'
  # UPDATE
  get 'comunas/:id/edit', to: 'comunas#edit', as: :comuna_edit
  patch 'comunas/:id', to: 'comunas#update'
  # DELETE
  delete 'comunas/:id', to: 'comunas#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",
                                                   registrations: "users/registrations" }
  # READ
  get 'users/index', to: 'users#index'
  get 'users/:id', to: 'users#show', as: 'user'

  # ------------------------------------------------------------------------------------------------
  devise_for :locals, path: 'locals', controllers: { sessions: "locals/sessions",
                                                     registrations: "locals/registrations" }
  # READ
  get 'locals/index', to: 'locals#index'
  get 'locals/:id', to: 'locals#show', as: 'local'
  # DELETE
  delete 'locals/:id', to: 'locals#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'matches', to: 'matches#create'
  # READ
  get 'matches/show_especial', to: 'matches#show_especial'
  get 'matches/:id', to: 'matches#management_local_view', as: 'match'
  # UPDATE
  patch 'matches/update', to: 'matches#update'
  patch 'matches/update_rejections', to: 'matches#update_rejections'
  # patch 'matches/management_local_view', to: 'matches#management_local_view'
  patch 'matches/update_local_and_boolean', to: 'matches#update_local_and_boolean'
  patch 'matches/accept_local', to: 'matches#accept_local'
  patch 'matches/change_local', to: 'matches#change_local'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'add_gusto', to: 'users#add_gusto'
  # DELETE
  delete 'remove_gusto', to: 'users#remove_gusto'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :liker, class_name: "User"
  belongs_to :liked, class_name: "User"
  belongs_to :local, optional: true
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def create
    @liker_id = params[:liker_id]
    @liked_id = params[:liked_id]
    @accept = params[:accept]
    @n_rejections = params[:n_rejections]
    @liked_bool_local = params[:liked_bool_local]
    @liker_bool_local = params[:liker_bool_local]

    @diccionario = { "accept" => @accept, "n_rejections" => @n_rejections, "liked_bool_local" =>
                     @liked_bool_local, "liker_bool_local" => @liker_bool_local,
                     "liker_id" => @liker_id, "liked_id" => @liked_id }

    @match = Match.create(@diccionario)
    if @match.save
      redirect_to users_index_path, notice: "Fue enviada la solicitud de match exitosamente"
    else
      redirect_to users_index_path, notice: "Ocurrió un error"
    end
  end

  def show_especial; end

  def update
    @match_id = params[:match_id]
    @accept = params[:accept]

    @diccionario = { "accept" => @accept }

    @match = Match.find(@match_id)

    if @match.update(@diccionario)
      redirect_to matches_show_especial_path, notice: "Se ha realizado el match correctamente!"
    else
      redirect_to matches_show_especial_path, notice: "Ocurrió un error"
    end
  end

  def update_rejections
    @match_id = params[:match_id]
    @n_rejections = params[:n_rejections]

    @diccionario = { "n_rejections" => @n_rejections }

    @match = Match.find(@match_id)

    if @match.update(@diccionario)
      redirect_to matches_show_especial_path, notice: "Se ha rechazado el match correctamente!"
    else
      redirect_to matches_show_especial_path, notice: "Ocurrió un error"
    end
  end

  def management_local_view
    @match_id = params[:id]
    @match = Match.find(@match_id)

    @locals = Local.all
  end

  def update_local_and_boolean
    @match_id = params[:match_id]
    @user_type = params[:user_type]
    @local_id = params[:local_id]

    @match = Match.find(@match_id)

    if @user_type == "liker"
      attribute = "liker_bool_local"
    elsif @user_type == "liked"
      attribute = "liked_bool_local"
    end
    @diccionario = { "local_id" => @local_id, attribute => true }
    if @match.update(@diccionario)
      redirect_to match_path(@match_id), notice: "Se ha actualizado el local correctamente!"
    else
      redirect_to match_path(@match_id), method: :patch, notice: "Ocurrió un error"
    end
  end

  def accept_local
    @match_id = params[:match_id]
    @user_type = params[:user_type]

    @match = Match.find(@match_id)

    if @user_type == "liker"
      attribute = "liker_bool_local"
    elsif @user_type == "liked"
      attribute = "liked_bool_local"
    end
    @diccionario = { attribute => true }
    if @match.update(@diccionario)
      redirect_to match_path(@match_id), notice: "Se ha actualizado el local correctamente!"
    else
      redirect_to match_path(@match_id), method: :patch, notice: "Ocurrió un error"
    end
  end

  def change_local
    @match_id = params[:match_id]
    @user_type = params[:user_type]
    @local_id = params[:local_id]

    @match = Match.find(@match_id)

    if  @user_type == "liker"
      attribute_a = "liker_bool_local"
      attribute_b = "liked_bool_local"
    elsif @user_type == "liked"
      attribute_a = "liked_bool_local"
      attribute_b = "liker_bool_local"
    end
    @diccionario = { attribute_a => true, attribute_b => false, "local_id" => @local_id }
    if @match.update(@diccionario)
      redirect_to match_path(@match_id), notice: "Se ha actualizado el local correctamente!"
    else
      redirect_to match_path(@match_id), method: :patch, notice: "Ocurrió un error"
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/management_local_view.html.erb
<% if current_user.id == @match.liker_id %>
    <% user_type = "liker" %>
<% elsif current_user.id == @match.liked_id %>
    <% user_type = "liked" %>
<% end %>

<% puts @match.local %>

<% if @match.local == nil %>

    <section id="match_img_2" class="hero is-fullheight">
      <div class="hero-body">
        <div class="container">
            <div class="box">
                <h1 class="title has-text-black">Debes seleccionar Local para la cita!</h1>
                <% @locals.each do |local| %>
                        <article class="media">
                          <div class="media-content">
                            <div class="content">
                              <p>
                                <h1 class="subtitle is-5 has-text-black"><%= local.nombre %></h1>
                                <%= local.descripcion %>
                              </p>
                            </div>
                            <nav class="level is-mobile">
                              <div class="level-left">
                                <a class="level-item">
                                    <button class="button">
                                        <%= link_to "Seleccionar Local", matches_update_local_and_boolean_path(:match_id => @match.id, :user_type => user_type, :local_id => local.id), method: :patch %> 
                                    </button>
                                </a>
                              </div>
                            </nav>
                          </div>
                        </article>
                <% end %> 
            </div>
            <button id="buttonuser" class="button">
                <%= link_to "Volver a la pagina de gestion de tus matches", matches_show_especial_path %>
            </button>
        </div>
      </div>
    </section>

<% elsif @match.local != nil && (@match.liker_bool_local == false || @match.liked_bool_local == false)%>

    <section id="match_img_2" class="hero is-primary is-fullheight">
      <div class="hero-body">
        <div class="container">
            <div class="box">
                <h1 class="title is-1 has-text-black"> Local seleccionado: <%= @match.local.nombre %></h1>

                <p>
                    <%= @match.local.descripcion %>.
                </p>

                <hr>

                <% if user_type == "liker" %>


                    <% if @match.liker_bool_local == false %>

                        <p class="subtitle has-text-black">Si te gusta el actual local, apreta el boton "Me gusta el local! O puedes seleccionar el que mas te guste en
                        la parte inferior"</p>

                        <br/>
                        <%= button_to 'Me gusta el local!', matches_accept_local_path(:match_id => @match.id, :user_type => user_type), method: :patch, class:"button" %>
                        <br/>
                    <% else %>

                        <p class="subtitle has-text-black">Estas de acuerdo con el local selecionado!</p>

                    <% end %>

                <% elsif user_type == "liked" %>
                
                    <% if @match.liked_bool_local == false %>

                        <p class="subtitle has-text-black">Si te gusta el actual local, apreta el boton "Me gusta el local!"</p>

                        <br/>
                        <%= button_to 'Me gusta el local!', matches_accept_local_path(:match_id => @match.id, :user_type => user_type), method: :patch, class:"button"  %>
                        <br/>

                    <% else %>

                        <p class="subtitle has-text-black">Estas de acuerdo con el local selecionado!</p>

                    <% end %>

                <% end %>
            </div>
            <div class="box">
                <% @locals.each do |local| %>
                        <article class="media">
                          <div class="media-content">
                            <div class="content">
                              <p>
                                <h1 class="subtitle is-5 has-text-black"><%= local.nombre %></h1>
                                <%= local.descripcion %>
                              </p>
                            </div>
                            <nav class="level is-mobile">
                              <div class="level-left">
                                <a class="level-item">
                                    <button class="button">
                                        <%= link_to "Cambiar a este Local", matches_change_local_path(:match_id => @match.id, :user_type => user_type, :local_id => local.id), method: :patch %>
                                    </button>
                                </a>
                              </div>
                            </nav>
                          </div>
                        </article>
                <% end %> 
            </div>
            <button id="buttonuser" class="button">
                <%= link_to "Volver a la pagina de gestion de tus matches", matches_show_especial_path %>
            </button>
        </div>
      </div>
    </section>         

<% elsif @match.local != nil && @match.liker_bool_local == true && @match.liked_bool_local == true%>

    <section id="match_img_2" class="hero is-fullheight">
      <div class="hero-body">
        <div class="container">
            <div class="box">
                <h1 class="title"> Todo listo! Mucha suerte en tu cita! </h1>

                <p>
                    <strong> Local Seleccionado: </strong>
                    <%= @match.local.nombre %>
                </p>
                <p>
                    <strong> Descripción del local: </strong>
                    <%= @match.local.descripcion %>Curabitur sapien felis, feugiat sed porta at, tristique sed augue. Vestibulum at lacinia tortor. Donec auctor convallis metus, eu efficitur lectus molestie id. Nunc ut neque vel lorem lobortis varius non in massa. Donec molestie commodo efficitur. Fusce mattis dolor ac viverra tincidunt. Aenean at venenatis tortor. 
                </p>
            </div>
        </div>
      </div>
    </section>

<% end %>

app/views/matches/show_especial.html.erb
<section id="match_img" class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h1 class="title has-text-white"> Te han llegado las siguientes posibilidades de matches! </h1> 
                <div class="box">
                  <div id="size_fixed" class="container">
                    <% current_user.liked_matches.each do |match| %>
                        <% if match.accept != true && match.n_rejections == 0%>
                            <article class="media">
                              <div class="media-left">
                                <% if match.liker.imagen.attached? %>
                                    <figure class="image is-64x64">
                                        <%= image_tag(match.liker.imagen)%>
                                    </figure>
                                <% else%>
                                    <figure class="image is-64x64">
                                        <img src="https://bulma.io/images/placeholders/128x128.png">
                                    </figure>
                                <% end %>
                              </div>
                              <div class="media-content">
                                <div class="content">
                                  <p>
                                    <strong><%= match.liker.nombre %></strong> <small><%match.liker.email%></small>
                                    <br>
                                    <%= match.liker.descripcion %>
                                  </p>
                                </div>
                                <nav class="level is-mobile">
                                  <div class="level-left">
                                    <a class="level-item">
                                      <%=  button_to 'Aceptar', matches_update_path(:match_id => match.id, :accept => true), method: :patch  %>
                                    </a>
                                    <a class="level-item">
                                      <%=  button_to 'Rechazar', matches_update_rejections_path(:match_id => match.id, :n_rejections => 1), method: :patch  %>
                                    </a>
                                  </div>
                                </nav>
                              </div>
                            </article>
                        <% else %>
                        <% end %>
                    <% end %> 
                  </div>
                </div>
            </div>
            <div class="column">
                <% all_matches = Array.new %>
                <% all_matches =  current_user.liked_matches + current_user.liker_matches%>
                <h1 class="title has-text-white"> Has hecho match con los siguientes usuario/s! </h1> 
                <div class="box">
                  <div id="size_fixed" class="container">
                    <% all_matches.each do |match| %>
                        <% if match.accept == true && match.liked_id == current_user.id%>
                            <article class="media">
                              <div class="media-left">
                                <% if match.liker.imagen.attached? %>
                                    <figure class="image is-64x64">
                                        <%= image_tag(match.liker.imagen)%>
                                    </figure>
                                <% else%>
                                    <figure class="image is-64x64">
                                        <img src="https://bulma.io/images/placeholders/128x128.png">
                                    </figure>
                                <% end %>
                              </div>
                              <div class="media-content">
                                <div class="content">
                                  <p>
                                    <strong><%= match.liker.nombre %></strong> <small><%match.liker.email%></small>
                                    <br>
                                    <%= match.liker.descripcion %>
                                  </p>
                                </div>
                                <nav class="level is-mobile">
                                  <div class="level-left">
                                    <a class="level-item">
                                      <%=  button_to 'Agendar local para la cita', match_path(match.id) , method: :get %>
                                    </a>
                                  </div>
                                </nav>
                              </div>
                            </article>
                        <% elsif match.accept == true && match.liker_id == current_user.id%>
                            <article class="media">
                              <div class="media-left">
                                <% if match.liked.imagen.attached? %>
                                    <figure class="image is-64x64">
                                        <%= image_tag(match.liked.imagen)%>
                                    </figure>
                                <% else%>
                                    <figure class="image is-64x64">
                                        <img src="https://bulma.io/images/placeholders/128x128.png">
                                    </figure>
                                <% end %>
                              </div>
                              <div class="media-content">
                                <div class="content">
                                  <p>
                                    <strong><%= match.liked.nombre %></strong> <small><%match.liked.email%></small>
                                    <br>
                                    <%= match.liked.descripcion %>
                                  </p>
                                </div>
                                <nav class="level is-mobile">
                                  <div class="level-left">
                                    <a class="level-item">
                                      <%=  button_to 'Agendar local para la cita', match_path(match.id) , method: :get %>
                                    </a>
                                  </div>
                                </nav>
                              </div>
                            </article>
                        <% end %>
                    <% end %> 
                  </div>
                </div>
            </div>
        </div>

        <button id="buttonuser" class="button">
            <%= link_to "Volver a la pagina principal", root_path %>
        </button>
    </div>
  </div>
</section>