config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # CREATE
  get 'reviews/new', to: 'reviews#new'
  post 'reviews', to: 'reviews#create'
  # READ
  get 'reviews/index'
  get 'reviews/:id', to: 'reviews#show', as: 'review'
  # UPDATE
  get 'reviews/:id/edit', to: 'reviews#edit', as: :review_edit
  patch 'reviews/:id', to: 'reviews#update'
  # DELETE
  delete 'reviews/:id', to: 'reviews#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'gustos/new', to: 'gustos#new'
  post 'gustos', to: 'gustos#create'
  # READ
  get 'gustos/index', to: 'gustos#index'
  get 'gustos/:id', to: 'gustos#show', as: 'gusto'
  # UPDATE
  get 'gustos/:id/edit', to: 'gustos#edit', as: :gusto_edit
  patch 'gustos/:id', to: 'gustos#update'
  # DELETE
  delete 'gustos/:id', to: 'gustos#destroy'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  get 'comunas/new', to: 'comunas#new'
  post 'comunas', to: 'comunas#create'
  # READ
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'
  # UPDATE
  get 'comunas/:id/edit', to: 'comunas#edit', as: :comuna_edit
  patch 'comunas/:id', to: 'comunas#update'
  # DELETE
  delete 'comunas/:id', to: 'comunas#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",
                                                   registrations: "users/registrations" }
  # READ
  get 'users/index', to: 'users#index'
  get 'users/:id', to: 'users#show', as: 'user'

  # ------------------------------------------------------------------------------------------------
  devise_for :locals, path: 'locals', controllers: { sessions: "locals/sessions",
                                                     registrations: "locals/registrations" }
  # READ
  get 'locals/index', to: 'locals#index'
  get 'locals/:id', to: 'locals#show', as: 'local'
  # DELETE
  delete 'locals/:id', to: 'locals#destroy'
  # ------------------------------------------------------------------------------------------------
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'matches', to: 'matches#create'
  # READ
  get 'matches/show_especial', to: 'matches#show_especial'
  get 'matches/:id', to: 'matches#management_local_view', as: 'match'
  # UPDATE
  patch 'matches/update', to: 'matches#update'
  patch 'matches/update_rejections', to: 'matches#update_rejections'
  # patch 'matches/management_local_view', to: 'matches#management_local_view'
  patch 'matches/update_local_and_boolean', to: 'matches#update_local_and_boolean'
  patch 'matches/accept_local', to: 'matches#accept_local'
  patch 'matches/change_local', to: 'matches#change_local'
  # ------------------------------------------------------------------------------------------------
  # CREATE
  post 'add_gusto', to: 'users#add_gusto'
  # DELETE
  delete 'remove_gusto', to: 'users#remove_gusto'
end

app/models/gusto.rb
class Gusto < ApplicationRecord
  has_many :user_gustos, dependent: :destroy
  has_many :user, through: :user_gustos
end

app/controllers/gustos_controller.rb
class GustosController < ApplicationController
  def new
    @gusto = Gusto.new
  end

  def create
    @gusto = Gusto.create(gusto_params)
    if @gusto.save
      redirect_to gustos_index_path, notice: "Gusto fue creada exitosamente"
    else
      redirect_to gustos_index_path, notice: "Ocurrió un error al crear el gusto"
    end
  end

  def index
    @gustos = Gusto.all
  end

  def show
    @gusto = Gusto.find(params[:id])
  end

  def edit
    @gusto = Gusto.find(params[:id])
  end

  def update
    @gusto = Gusto.find(params[:id])
    if @gusto.update(gusto_params)
      redirect_to gusto_path(@gusto.id), notice: "Gusto modificado con éxito"
    else
      redirect_to gusto_path(@gusto.id), notice: "Ocurrió un error al modificar el gusto"
    end
  end

  def destroy
    @gusto = Gusto.find(params[:id])
    @gusto.destroy
    redirect_to gustos_index_path, notice: "Gusto eliminado con éxito"
  end

  private

  def gusto_params
    params.require(:gusto).permit(:nombre, :descripcion)
  end
end

app/helpers/gustos_helper.rb
module GustosHelper
end

app/views/gustos/edit.html.erb
<h1>Editando Gusto existente</h1>

<%= form_with(model: @gusto, method: :patch) do |f| %>
  <div class="field" >
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field" >
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br/>
<%= link_to "Volver al listado de Gustos", gustos_index_path %>

app/views/gustos/index.html.erb
<% if current_user %>
  <section id="match_img" class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
          <div class="columns">
              <div class="column">
                  <h1 class="title has-text-white"> Estos son tus Gustos! </h1> 
                  <div class="box">
                    <div id="size_fixed" class="container">
                      <% current_user.gustos.each do |gusto| %>
                        <article class="media">
                          <div class="media-content">
                            <div class="content">
                              <p>
                                <h6><%= gusto.nombre %></h6>
                                <%= gusto.descripcion %>
                              </p>
                            </div>
                            <nav class="level is-mobile">
                              <div class="level-left">
                                <div class="level-item">
                                  <button class="button is-danger">
                                    <%= link_to 'Quitar gusto', remove_gusto_path(user_id: current_user.id, gusto_id: gusto.id), method: :delete, class:"has-text-white" %>
                                  </button>
                                </div>
                                <div class="level-item">
                                  <button class="button is-info">
                                    <%= link_to "Ver detalles", gusto_path(gusto.id), class:"has-text-white"%>
                                  </button>
                                </div>
                              </div>
                            </nav>
                          </div>
                        </article>
                      <% end %>
                    </div>
                  </div>
              </div>
              <div class="column">
                  <h1 class="title has-text-white"> Puedes tomar de aquí el que quieras! </h1> 
                  <div class="box">
                    <div id="size_fixed" class="container">
                      <% @gustos.each do |gusto| %>
                        <article class="media">
                          <div class="media-content">
                            <div class="content">
                              <p>
                                <h6><%= gusto.nombre %></h6>
                                <%= gusto.descripcion %>
                              </p>
                            </div>
                            <nav class="level is-mobile">
                              <div class="level-left">
                                <div class="level-item">
                                  <button class="button is-primary">
                                    <%= link_to 'Agregar gusto', add_gusto_path(user_id: current_user.id, gusto_id: gusto.id), method: :post, class:"has-text-white" %>
                                  </button>
                                </div>
                                <div class="level-item">
                                  <button class="button is-info">
                                    <%= link_to "Ver detalles", gusto_path(gusto.id), class:"has-text-white" %>
                                  </button>
                                </div>
                              </div>
                            </nav>
                          </div>
                        </article>
                      <% end %>
                    </div>
                  </div>
              </div>
          </div>

          <button id="buttonuser" class="button">
              <%= link_to "Volver a la pagina principal", root_path %>
          </button>
          <% if current_admin %>
            <button id="buttonuser" class="button">
              <%= link_to "Crear Nuevo Gusto", gustos_new_path %>
            </button>
          <% end %>
      </div>
    </div>
  </section>
<% else %>
  <section id="match_img" class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
        <h1 class="title has-text-white"> Mira todos los gustos que hay! </h1> 
        <div class="box">
          <div id="size_fixed" class="container">
            <% @gustos.each do |gusto| %>
              <article class="media">
                <div class="media-content">
                  <div class="content">
                    <p>
                      <h6><%= gusto.nombre %></h6>
                      <%= gusto.descripcion %>
                    </p>
                  </div>
                  <nav class="level is-mobile">
                    <div class="level-left">
                      <div class="level-item">
                        <% if current_user %>
                          <button class="button is-primary">
                            <%= link_to 'Agregar gusto', add_gusto_path(user_id: current_user.id, gusto_id: gusto.id), method: :post, class:"has-text-white" %>
                          </button>
                        <% end %>
                      </div>
                      <div class="level-item">
                        <button class="button is-info">
                          <%= link_to "Ver detalles", gusto_path(gusto.id), class:"has-text-white" %>
                        </button>
                      </div>
                    </div>
                  </nav>
                </div>
              </article>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

<% end %>

app/views/gustos/new.html.erb
<h1>Creando Nuevo Gusto</h1>

<%= form_with(model: @gusto, method: :post) do |f| %>
  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to "Volver al listado de comunas", gustos_index_path %>

app/views/gustos/show.html.erb
<section id="user_index_img" class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
                <h1 class="title is-1"><%= @gusto.nombre %></h1>
                <%= @gusto.descripcion %>
            </div>
          </div>
        </article>

      </div>
        <button id="buttonuser" class="button">
          <%= link_to "Volver al listado de gustos", gustos_index_path %>
        </button>
      <% if current_admin %>
        <button id="buttonuser" class="button">
          <%= link_to "Editar este gusto", gusto_edit_path(@gusto.id) %>
        </button>
        <button id="buttonuser" class="button">
          <%= link_to "Eliminar este Gusto", gusto_path(@gusto.id), method: :delete, data: {confirm: "Está seguro?"} %>
        </button>
    <% end %>
    </div>
  </div>
</section>